package com.myorg.commonapp.core.mapper;

import com.myorg.commonapp.bean.po.AdminUserInfo;
import com.myorg.commonapp.bean.po.AdminUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AdminUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    int countByExample(AdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    int deleteByExample(AdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    @Delete({
        "delete from admin_user_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    @Insert({
        "insert into admin_user_info (username, password)",
        "values (#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AdminUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    int insertSelective(AdminUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    List<AdminUserInfo> selectByExample(AdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    @Select({
        "select",
        "id, username, password",
        "from admin_user_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    AdminUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") AdminUserInfo record, @Param("example") AdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    int updateByExample(@Param("record") AdminUserInfo record, @Param("example") AdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    int updateByPrimaryKeySelective(AdminUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_info
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    @Update({
        "update admin_user_info",
        "set username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AdminUserInfo record);
}