package com.myorg.commonapp.core.mapper;

import com.myorg.commonapp.bean.po.Authorities;
import com.myorg.commonapp.bean.po.AuthoritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    int countByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    int deleteByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    @Delete({
        "delete from authorities",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    @Insert({
        "insert into authorities (authorities_name, authorities_desc, ",
        "enabled, is_system)",
        "values (#{authoritiesName,jdbcType=VARCHAR}, #{authoritiesDesc,jdbcType=VARCHAR}, ",
        "#{enabled,jdbcType=INTEGER}, #{isSystem,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    int insertSelective(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    List<Authorities> selectByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    @Select({
        "select",
        "id, authorities_name, authorities_desc, enabled, is_system",
        "from authorities",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Authorities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    int updateByExample(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    int updateByPrimaryKeySelective(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    @Update({
        "update authorities",
        "set authorities_name = #{authoritiesName,jdbcType=VARCHAR},",
          "authorities_desc = #{authoritiesDesc,jdbcType=VARCHAR},",
          "enabled = #{enabled,jdbcType=INTEGER},",
          "is_system = #{isSystem,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Authorities record);
}