package com.myorg.commonapp.core.mapper;

import com.myorg.commonapp.bean.po.SysResource;
import com.myorg.commonapp.bean.po.SysResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    int countByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    int deleteByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    @Delete({
        "delete from sys_resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    @Insert({
        "insert into sys_resource (resource_name, resource_url, ",
        "resource_type, priority, ",
        "resource_desc, enable)",
        "values (#{resourceName,jdbcType=VARCHAR}, #{resourceUrl,jdbcType=VARCHAR}, ",
        "#{resourceType,jdbcType=VARCHAR}, #{priority,jdbcType=INTEGER}, ",
        "#{resourceDesc,jdbcType=VARCHAR}, #{enable,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    List<SysResource> selectByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    @Select({
        "select",
        "id, resource_name, resource_url, resource_type, priority, resource_desc, enable",
        "from sys_resource",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SysResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    int updateByExample(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Wed Jul 29 16:06:33 CST 2015
     */
    @Update({
        "update sys_resource",
        "set resource_name = #{resourceName,jdbcType=VARCHAR},",
          "resource_url = #{resourceUrl,jdbcType=VARCHAR},",
          "resource_type = #{resourceType,jdbcType=VARCHAR},",
          "priority = #{priority,jdbcType=INTEGER},",
          "resource_desc = #{resourceDesc,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysResource record);
}