package com.myorg.commonapp.bean.po;

public class AdminUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_info.id
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_info.username
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_info.password
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_info.id
     *
     * @return the value of admin_user_info.id
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_info.id
     *
     * @param id the value for admin_user_info.id
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_info.username
     *
     * @return the value of admin_user_info.username
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_info.username
     *
     * @param username the value for admin_user_info.username
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_info.password
     *
     * @return the value of admin_user_info.password
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_info.password
     *
     * @param password the value for admin_user_info.password
     *
     * @mbggenerated Thu Jul 02 11:25:24 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}