package com.myorg.commonapp.bean.po;

import com.myorg.commonapp.bean.pojo.BasePojo;

public class Authorities extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorities.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorities.authorities_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String authoritiesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorities.authorities_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String authoritiesDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorities.enabled
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorities.is_system
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer isSystem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorities.id
     *
     * @return the value of authorities.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorities.id
     *
     * @param id the value for authorities.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorities.authorities_name
     *
     * @return the value of authorities.authorities_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getAuthoritiesName() {
        return authoritiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorities.authorities_name
     *
     * @param authoritiesName the value for authorities.authorities_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setAuthoritiesName(String authoritiesName) {
        this.authoritiesName = authoritiesName == null ? null : authoritiesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorities.authorities_desc
     *
     * @return the value of authorities.authorities_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getAuthoritiesDesc() {
        return authoritiesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorities.authorities_desc
     *
     * @param authoritiesDesc the value for authorities.authorities_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setAuthoritiesDesc(String authoritiesDesc) {
        this.authoritiesDesc = authoritiesDesc == null ? null : authoritiesDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorities.enabled
     *
     * @return the value of authorities.enabled
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorities.enabled
     *
     * @param enabled the value for authorities.enabled
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorities.is_system
     *
     * @return the value of authorities.is_system
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorities.is_system
     *
     * @param isSystem the value for authorities.is_system
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setIsSystem(Integer isSystem) {
        this.isSystem = isSystem;
    }
}