package com.myorg.commonapp.bean.po;

import com.myorg.commonapp.bean.pojo.BasePojo;

public class Resources extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resource_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resource_type
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.priority
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resource_url
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.resource_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.enable
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.id
     *
     * @return the value of resources.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.id
     *
     * @param id the value for resources.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resource_name
     *
     * @return the value of resources.resource_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resource_name
     *
     * @param resourceName the value for resources.resource_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resource_type
     *
     * @return the value of resources.resource_type
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resource_type
     *
     * @param resourceType the value for resources.resource_type
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.priority
     *
     * @return the value of resources.priority
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.priority
     *
     * @param priority the value for resources.priority
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resource_url
     *
     * @return the value of resources.resource_url
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resource_url
     *
     * @param resourceUrl the value for resources.resource_url
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.resource_desc
     *
     * @return the value of resources.resource_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.resource_desc
     *
     * @param resourceDesc the value for resources.resource_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc == null ? null : resourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.enable
     *
     * @return the value of resources.enable
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.enable
     *
     * @param enable the value for resources.enable
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}