package com.myorg.commonapp.bean.po;

import com.myorg.commonapp.bean.pojo.BasePojo;

public class Roles extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.enable
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.is_system
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    private Integer isSystem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_name
     *
     * @return the value of roles.role_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_name
     *
     * @param roleName the value for roles.role_name
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role_desc
     *
     * @return the value of roles.role_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role_desc
     *
     * @param roleDesc the value for roles.role_desc
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.enable
     *
     * @return the value of roles.enable
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.enable
     *
     * @param enable the value for roles.enable
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.is_system
     *
     * @return the value of roles.is_system
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public Integer getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.is_system
     *
     * @param isSystem the value for roles.is_system
     *
     * @mbggenerated Thu Jul 16 22:22:20 CST 2015
     */
    public void setIsSystem(Integer isSystem) {
        this.isSystem = isSystem;
    }
}