package com.myorg.commonapp.bean.po;

public class SysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.id
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_id
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_name
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_permission
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private String resourcePermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_url
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.priority
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.resource_desc
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.enable
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_id
     *
     * @return the value of sys_resource.parent_id
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_id
     *
     * @param parentId the value for sys_resource.parent_id
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_name
     *
     * @return the value of sys_resource.resource_name
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_name
     *
     * @param resourceName the value for sys_resource.resource_name
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_permission
     *
     * @return the value of sys_resource.resource_permission
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public String getResourcePermission() {
        return resourcePermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_permission
     *
     * @param resourcePermission the value for sys_resource.resource_permission
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setResourcePermission(String resourcePermission) {
        this.resourcePermission = resourcePermission == null ? null : resourcePermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_url
     *
     * @return the value of sys_resource.resource_url
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_url
     *
     * @param resourceUrl the value for sys_resource.resource_url
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.priority
     *
     * @return the value of sys_resource.priority
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.priority
     *
     * @param priority the value for sys_resource.priority
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.resource_desc
     *
     * @return the value of sys_resource.resource_desc
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.resource_desc
     *
     * @param resourceDesc the value for sys_resource.resource_desc
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc == null ? null : resourceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.enable
     *
     * @return the value of sys_resource.enable
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.enable
     *
     * @param enable the value for sys_resource.enable
     *
     * @mbggenerated Thu Jul 30 16:40:12 CST 2015
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}